apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: ""
  capacity:  
    storage: {{ .Values.pvcStorage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mysqldata"
