apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-wordpress
  name: mysql-service
spec:
  ports:
  - port: {{.Values.servicedbPort}}
    protocol: TCP
    targetPort: {{.Values.servicedbPort}}
  selector:
    app: backend
  type: NodePort
