apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-wordpress
  name: wordpress
spec:
  replicas: {{.Values.replicawpCount}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: wordpress:5.1.1-php7.3-apache
        name: wordpress
        
        
