apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-wordpress
  name: wordpress-service
spec:
  ports:
  - port: {{.Values.servicewpPort}}
    protocol: TCP
    targetPort: {{.Values.servicewpPort}}
  selector:
    app: frontend
  type: NodePort
